name: manus
channels:
  - conda-forge
  - defaults
dependencies:
  - annotated-types
  - anyio
  - bibtexparser
  - bzip2
  - ca-certificates
  - certifi
  - distro
  - expat
  - h11
  - httpcore
  - httpx
  - icu
  - idna
  - libcxx
  - libffi
  - libiconv
  - libxml2
  - libxslt
  - lxml
  - ncurses
  - openai
  - openssl
  - pandoc
  - pathlib
  - pip
  - pydantic
  - pydantic-core
  - pypandoc
  - python
  - python-docx
  - readline
  - setuptools
  - sniffio
  - sqlite
  - tk
  - tqdm
  - typing-extensions
  - typing_extensions
  - tzdata
  - wheel
  - xz
  - zlib
